# Generated by Django 3.2.18 on 2023-03-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawLots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_lots_user_ids', models.TextField(verbose_name='抽签用户id列表')),
                ('draw_lots_date', models.DateTimeField(auto_now_add=True, verbose_name='抽签时间')),
                ('effective_date', models.DateTimeField(verbose_name='生效时间')),
            ],
            options={
                'db_table': 'draw_lots',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名称')),
                ('name', models.CharField(max_length=64, verbose_name='中文名称')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('phone', models.IntegerField(max_length=11, verbose_name='用户手机号')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_call_date', models.DateTimeField(verbose_name='值班时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users', verbose_name='用户')),
            ],
            options={
                'db_table': 'on_call_schedule',
            },
        ),
    ]
