# Generated by Django 3.2.18 on 2023-03-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='用户手机号'),
        ),
    ]
