# Generated by Django 3.2.18 on 2023-03-27 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230327_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallschedule',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
